- name: Check if OpenSCAP is installedml
  ansible.builtin.command: rpm -q openscap-scanner
  register: oscap_installed
  ignore_errors: true

- name: Install OpenSCAP and SCAP Security Guide
  ansible.builtin.command: >
    dnf install -y openscap-scanner scap-security-guide
  when: oscap_installed.rc != 0
