#cloud-config
packages:
  - python3
  - git
  - ansible-core

users:
  - name: ansible
    groups: [wheel, adm]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh-authorized-keys:
      - ${ssh_pubkey}

ssh_pwauth: false

runcmd:
  - hostnamectl set-hostname controller

