version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-builder:latest

dependencies:
  ansible_core:
    package_pip: ansible-core
  
  ansible_runner:
    package_pip: ansible-runner

  system:
    - sshpass
    - git
    - openssh-clients

  python:
    - requests
    - boto3

  galaxy:
    collections:
      - requirements.yml
